server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: app-client
  lifecycle:
    timeout-per-shutdown-phase: 15s

services:
  app-server: http://localhost:8081/server

management:
  endpoints:
        web:
            exposure:
                include: health

logging:
  level:
    root: INFO
    com.erojas.lab.appclient: DEBUG