server:
  port: 8080

spring:
  application:
    name: app-client

services:
  app-server: http://localhost:8081/server

logging:
  level:
    root: INFO
    com.erojas.lab.appclient: DEBUG

---
spring:
  config:
    activate:
      on-profile: docker


server:
  port: 8080

services:
  app-server: http://app-server:8080/server