apiVersion: v1
kind: Service
metadata:
  name: app-client
  labels:
    app: app-client
spec:
  type: ClusterIP
  selector:
    app: app-client
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
